# Generated by Django 4.0.3 on 2022-04-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['formatted_name', 'last_name', 'first_name']},
        ),
        migrations.AddField(
            model_name='contact',
            name='formatted_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contact',
            name='person_type',
            field=models.CharField(choices=[('Natural', 'Natural person'), ('Legal', 'Legal person')], default='Natural', max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
