# Generated by Django 4.0.3 on 2022-04-16 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0002_alter_contact_options_contact_formatted_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='addressbook.contact'),
        ),
        migrations.AlterField(
            model_name='email',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='addressbook.contact'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phonenumbers', to='addressbook.contact'),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socialnetworks', to='addressbook.contact'),
        ),
        migrations.AlterField(
            model_name='website',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websites', to='addressbook.contact'),
        ),
    ]
