# Generated by Django 4.0.5 on 2022-06-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0003_facility_node'),
        ('addressbook', '0004_email_facility_phonenumber_facility_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='facility',
            field=models.ManyToManyField(blank=True, to='facility.facility'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='facility',
            field=models.ManyToManyField(blank=True, to='facility.facility'),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='facility',
            field=models.ManyToManyField(blank=True, to='facility.facility'),
        ),
        migrations.AlterField(
            model_name='website',
            name='facility',
            field=models.ManyToManyField(blank=True, to='facility.facility'),
        ),
    ]
