# Generated by Django 4.0.6 on 2022-08-05 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_role_description_en_role_description_fr_and_more'),
        ('facility', '0003_facility_node'),
        ('addressbook', '0007_alter_socialnetwork_handle_alter_socialnetwork_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, unique=True)),
                ('label', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AppStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=255)),
                ('app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='addressbook.app')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='addressbook.contact')),
                ('facility', models.ManyToManyField(blank=True, to='facility.facility')),
                ('roles', models.ManyToManyField(blank=True, help_text='Roles allowed so see the related object', to='access.role')),
            ],
        ),
        migrations.CreateModel(
            name='AppLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='addressbook.appstore')),
            ],
        ),
        migrations.AddField(
            model_name='app',
            name='links',
            field=models.ManyToManyField(to='addressbook.applink'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('app__isnull', True), ('phone__isnull', True), ('url__isnull', False)), models.Q(('app__isnull', True), ('phone__isnull', False), ('url__isnull', True)), models.Q(('app__isnull', False), ('phone__isnull', True), ('url__isnull', True)), _connector='OR'), name='one_and_only_one_field_not_null_among_url_phone_app'),
        ),
    ]
