# Generated by Django 4.0.6 on 2022-08-11 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0009_remove_appointment_one_and_only_one_field_not_null_among_url_phone_app_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='email',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='socialnetwork',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='website',
            name='facility',
        ),
    ]
