# Generated by Django 4.0.6 on 2022-08-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0010_remove_appointment_facility_remove_email_facility_and_more'),
        ('facility', '0004_organization_remove_facility_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='organization',
            field=models.ManyToManyField(blank=True, to='facility.organization'),
        ),
        migrations.AddField(
            model_name='email',
            name='organization',
            field=models.ManyToManyField(blank=True, to='facility.organization'),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='organization',
            field=models.ManyToManyField(blank=True, to='facility.organization'),
        ),
        migrations.AddField(
            model_name='profile',
            name='organization',
            field=models.ManyToManyField(blank=True, to='facility.organization'),
        ),
        migrations.AddField(
            model_name='socialnetwork',
            name='organization',
            field=models.ManyToManyField(blank=True, to='facility.organization'),
        ),
        migrations.AddField(
            model_name='website',
            name='organization',
            field=models.ManyToManyField(blank=True, to='facility.organization'),
        ),
    ]
