# Generated by Django 4.1 on 2022-09-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0012_alter_address_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=16, null=True),
        ),
    ]
