# Generated by Django 4.1 on 2022-09-13 13:05

import addressbook.models
from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0015_alter_address_latitude_alter_address_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='profile_image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to=addressbook.models.profile_image_path),
        ),
    ]
