# Generated by Django 4.1.1 on 2022-11-07 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0018_contact_formatted_name_definite_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetwork',
            name='type',
            field=models.CharField(choices=[('S', 'Skype'), ('T', 'Twitter'), ('LI', 'LinkedIn'), ('F', 'Facebook'), ('P', 'Pinterest'), ('I', 'Instagram'), ('YT', 'YouTube'), ('TT', 'TikTok'), ('SC', 'Snapchat'), ('TH', 'Twitch')], max_length=255),
        ),
    ]
