# Generated by Django 4.1.9 on 2023-05-05 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0019_alter_socialnetwork_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='type',
            field=models.CharField(choices=[('P', 'Personal'), ('W', 'Work'), ('M', 'MSSanté')], max_length=255),
        ),
    ]
