# Generated by Django 4.1.9 on 2023-05-14 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0020_alter_email_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='type',
            field=models.CharField(choices=[('Home', 'Address'), ('Work', 'Address')], max_length=255),
        ),
    ]
