# Generated by Django 4.1.1 on 2022-10-21 18:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opengraph', '0002_alter_twittercard_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='twittercard',
            name='twitter_description',
            field=models.TextField(blank=True, max_length=200, validators=[django.core.validators.MaxLengthValidator(200, message='200 characters max!')]),
        ),
        migrations.AlterField(
            model_name='twittercard',
            name='description',
            field=models.TextField(blank=True, max_length=160, validators=[django.core.validators.MaxLengthValidator(160, message='160 characters max!')]),
        ),
    ]
