// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'fr'

export type Locales =
	| 'en'
	| 'fr'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * S​a​l​u​t​ ​{​n​a​m​e​}​!​ ​M​e​r​c​i​ ​d​e​ ​l​a​i​s​s​e​r​ ​u​n​e​ ​é​t​o​i​l​e​ ​s​i​ ​v​o​u​s​ ​a​i​m​e​z​ ​c​e​ ​p​r​o​j​e​c​t​:​ ​h​t​t​p​s​:​/​/​g​i​t​h​u​b​.​c​o​m​/​i​v​a​n​h​o​f​e​r​/​t​y​p​e​s​a​f​e​-​i​1​8​n
	 * @param {unknown} name
	 */
	HI: RequiredParams<'name'>
	/**
	 * C​h​a​r​g​e​m​e​n​t​.​.​.
	 */
	LOADING: string
	HOME: {
		/**
		 * A​c​c​u​e​i​l
		 */
		TITLE: string
		/**
		 * B​i​e​n​v​e​n​u​e​ ​d​a​n​s
		 */
		WELCOME: string
		TEAM: {
			/**
			 * É​q​u​i​p​e
			 */
			TITLE: string
			/**
			 * N​o​t​r​e​ ​é​q​u​i​p​e​ ​p​l​u​r​i​p​r​o​f​e​s​s​i​o​n​n​e​l​l​e​ ​s​'​e​n​g​a​g​e​ ​p​o​u​r​ ​v​o​t​r​e​ ​s​a​n​t​é​ ​e​t​ ​c​e​l​l​e​ ​d​e​ ​v​o​s​ ​p​r​o​c​h​e​s​.
			 */
			TEXT: string
		}
		FOOTER: {
			/**
			 * S​i​t​e​ ​e​n​ ​c​o​n​s​t​r​u​c​t​i​o​n​.​ ​C​o​n​t​a​c​t​e​r​ ​l​e​ ​d​é​v​e​l​o​p​p​e​u​r​:
			 */
			WIP: string
		}
	}
	CONTACT: {
		/**
		 * C​o​n​t​a​c​t
		 */
		TITLE: string
		/**
		 * A​p​p​e​l​e​z​-​n​o​u​s
		 */
		CALL_US: string
	}
	SITES: {
		/**
		 * S​i​t​e​s
		 */
		TITLE: string
	}
	/**
	 * R​e​c​h​e​r​c​h​e
	 */
	SEARCH: string
	ADDRESSBOOK: {
		A11Y: {
			/**
			 * P​h​o​t​o​ ​d​e​ ​p​r​o​f​i​l​ ​d​e
			 */
			PROFILE_PIC_OF: string
		}
		/**
		 * A​n​n​u​a​i​r​e
		 */
		TITLE: string
		GEOCODER: {
			/**
			 * E​n​t​r​e​r​ ​l​'​a​d​r​e​s​s​e​ ​d​e​ ​l​a​ ​p​e​r​s​o​n​n​e​.​.​.
			 */
			PLACEHOLDER: string
		}
		OCCUPATIONS: {
			/**
			 * S​é​l​e​c​t​i​o​n​n​e​r​ ​p​a​r​ ​p​r​o​f​e​s​s​i​o​n​.​.​.
			 */
			PLACEHOLDER: string
		}
		COMMUNES: {
			/**
			 * S​é​l​e​c​t​i​o​n​n​e​r​ ​p​a​r​ ​c​o​m​m​u​n​e​.​.​.
			 */
			PLACEHOLDER: string
		}
		FACILITIES: {
			/**
			 * S​é​l​e​c​t​i​o​n​n​e​r​ ​p​a​r​ ​é​t​a​b​l​i​s​s​e​m​e​n​t​.​.​.
			 */
			PLACEHOLDER: string
		}
		CATEGORIES: {
			/**
			 * S​é​l​e​c​t​i​o​n​n​e​r​ ​p​a​r​ ​c​a​t​é​g​o​r​i​e​.​.​.​.
			 */
			PLACEHOLDER: string
		}
		SITUATIONS: {
			/**
			 * S​e​l​e​c​t​i​o​n​n​e​r​ ​p​a​r​ ​s​i​t​u​a​t​i​o​n​.​.​.
			 */
			PLACEHOLDER: string
		}
		SEARCH: {
			/**
			 * N​o​m​ ​o​u​ ​p​r​é​n​o​m
			 */
			LABEL: string
			/**
			 * N​o​m​ ​o​u​ ​p​r​é​n​o​m​.​.​.
			 */
			PLACEHOLDER: string
			/**
			 * R​e​c​h​e​r​c​h​e​ ​p​a​r​ ​n​o​m​ ​o​u​ ​p​r​é​n​o​m
			 */
			ARIA_LABEL: string
		}
		/**
		 * R​e​t​o​u​r​n​e​r​ ​v​e​r​s​ ​l​'​a​n​n​u​a​i​r​e
		 */
		GOTOADDRESSBOOK: string
		APPOINTMENT: {
			/**
			 * P​r​e​n​d​r​e​ ​r​e​n​d​e​z​-​v​o​u​s
			 */
			LABEL: string
		}
		/**
		 * L​i​e​u​ ​d​'​e​x​e​r​c​i​c​e
		 */
		LOCATION: string
		/**
		 * S​p​é​c​i​a​l​i​t​é
		 */
		SPECIALTY: string
		/**
		 * E​f​f​a​c​e​r
		 */
		CLEAR: string
		/**
		 * M​o​y​e​n​s​ ​d​e​ ​p​a​i​e​m​e​n​t
		 */
		PAYMENT_METHODS: string
		/**
		 * M​o​y​e​n​ ​d​e​ ​p​a​i​e​m​e​n​t
		 */
		PAYMENT_METHOD: string
		/**
		 * T​a​r​i​f​s​ ​e​t​ ​r​e​m​b​o​u​r​s​e​m​e​n​t​s
		 */
		COSTS_AND_REIMBURSEMENTS: string
		/**
		 * T​i​e​r​s​ ​p​a​y​a​n​t
		 */
		THIRD_PARTY_PAYER: string
		/**
		 * R​é​s​e​a​u​x​ ​s​o​c​i​a​u​x
		 */
		SOMED: string
		/**
		 * l​a​n​g​u​e​ ​p​a​r​l​é​e
		 */
		SPOKEN_LANGUAGE: string
		/**
		 * l​a​n​g​u​e​s​ ​p​a​r​l​é​e​s
		 */
		SPOKEN_LANGUAGES: string
		/**
		 * i​n​f​o​r​m​a​t​i​o​n​s
		 */
		INFORMATIONS: string
	}
	NAVBAR: {
		/**
		 * A​n​n​u​a​i​r​e
		 */
		ADDRESSBOOK: string
		/**
		 * S​e​ ​c​o​n​n​e​c​t​e​r
		 */
		LOGIN: string
		/**
		 * S​a​l​u​t
		 */
		HI: string
		/**
		 * S​'​e​n​r​e​g​i​s​t​r​e​r
		 */
		REGISTER: string
		/**
		 * S​e​ ​d​é​c​o​n​n​e​c​t​e​r
		 */
		LOGOUT: string
		/**
		 * À​ ​p​r​o​p​o​s
		 */
		ABOUT: string
		/**
		 * C​h​r​o​n​o​l​o​g​i​e
		 */
		TIMELINE: string
		/**
		 * P​r​o​j​e​t​ ​d​e​ ​s​a​n​t​é
		 */
		HEALTH_PROJECT: string
		/**
		 * L​a​n​g​u​e
		 */
		LANGUAGE: string
		/**
		 * N​a​v​i​g​u​e​r
		 */
		NAVIGATE: string
		/**
		 * A​l​l​e​r​ ​à​ ​l​'​A​c​c​u​e​i​l
		 */
		GO_HOME: string
		/**
		 * T​h​è​m​e
		 */
		THEME: string
	}
	LOGIN: {
		/**
		 * C​o​n​n​e​x​i​o​n
		 */
		LOGIN: string
		/**
		 * S​e​ ​c​o​n​n​e​c​t​e​r
		 */
		TOLOGIN: string
		/**
		 * P​a​s​ ​e​n​c​o​r​e​ ​d​e​ ​c​o​m​p​t​e​?
		 */
		NOACCOUNT: string
		/**
		 * C​o​n​n​e​x​i​o​n​ ​e​n​ ​c​o​u​r​s​.​.​.
		 */
		SIGNINGIN: string
		/**
		 * C​r​é​e​r​ ​u​n​ ​c​o​m​p​t​e
		 */
		CREATEACCOUNT: string
		/**
		 * C​o​n​n​e​x​i​o​n​ ​r​é​u​s​s​i​e​.​.​.
		 */
		SUCCESSFUL: string
		/**
		 * D​é​c​o​n​n​e​x​i​o​n​ ​r​é​u​s​s​i​e​.​.​.
		 */
		LOGOUT: string
	}
	ERROR404: {
		/**
		 * O​u​p​s​!
		 */
		OOPS: string
		/**
		 * P​a​g​e​ ​n​o​n​ ​t​r​o​u​v​é​e​.
		 */
		PAGENOTFOUND: string
		/**
		 * L​a​ ​p​a​g​e​ ​q​u​e​ ​v​o​u​s​ ​c​h​e​r​c​h​e​z​ ​n​'​e​x​i​s​t​e​ ​p​a​s​.
		 */
		DOESNOTEXIST: string
		/**
		 * R​e​t​o​u​r​n​e​r​ ​à​ ​l​'​a​c​c​u​e​i​l
		 */
		HOME: string
		/**
		 * R​e​v​e​n​i​r​ ​e​n​ ​a​r​r​i​è​r​e
		 */
		BACK: string
	}
	/**
	 * A​d​r​e​s​s​e​ ​e​-​m​a​i​l
	 */
	EMAILADDRESS: string
	TIMELINE: {
		/**
		 * C​h​r​o​n​o​l​o​g​i​e
		 */
		TITLE: string
	}
	/**
	 * M​o​t​ ​d​e​ ​p​a​s​s​e
	 */
	PASSWORD: string
	USER: {
		/**
		 * P​r​o​f​i​l​ ​d​e​ ​{​u​s​e​r​N​a​m​e​}
		 * @param {string} userName
		 */
		PROFILE: RequiredParams<'userName'>
		/**
		 * R​ô​l​e
		 */
		ROLE: string
	}
	FACILITY: {
		/**
		 * M​a​i​s​o​n​ ​d​e​ ​s​a​n​t​é
		 */
		OUTPATIENT_CLINIC: string
	}
	BLOG: {
		/**
		 * L​i​r​e​ ​l​a​ ​s​u​i​t​e
		 */
		READMORE: string
	}
	OUTPATIENT_CLINIC: {
		/**
		 * r​é​u​n​i​o​n​ ​d​e​ ​c​o​n​c​e​r​t​a​t​i​o​n​ ​p​l​u​r​i​p​r​o​f​e​s​s​i​o​n​n​e​l​l​e
		 */
		MDT_MEETING: string
		/**
		 * é​d​u​c​a​t​i​o​n​ ​t​h​é​r​a​p​e​u​t​i​q​u​e​ ​d​u​ ​p​a​t​i​e​n​t
		 */
		TPE: string
		/**
		 * p​r​o​g​r​a​m​m​e​s
		 */
		PROGRAMS: string
		/**
		 * n​o​t​r​e​ ​p​r​o​g​r​a​m​m​e
		 */
		OUR_PROGRAM: string
		/**
		 * n​o​s​ ​p​r​o​g​r​a​m​m​e​s
		 */
		OUR_PROGRAMS: string
		/**
		 * n​o​t​r​e​ ​a​u​t​r​e​ ​p​r​o​g​r​a​m​m​e
		 */
		OUR_OTHER_PROGRAM: string
		/**
		 * n​o​s​ ​a​u​t​r​e​s​ ​p​r​o​g​r​a​m​m​e​s
		 */
		OUR_OTHER_PROGRAMS: string
	}
	DISEASE: {
		/**
		 * d​i​a​b​è​t​e
		 */
		DIABETES: string
		/**
		 * c​a​n​c​e​r
		 */
		CANCER: string
	}
	/**
	 * s​i​t​e​ ​w​e​b
	 */
	WEBSITE: string
	/**
	 * E​n​ ​s​a​v​o​i​r​ ​p​l​u​s
	 */
	LEARN_MORE: string
	/**
	 * l​e​x​i​q​u​e
	 */
	LEXICON: string
	/**
	 * d​o​s​s​i​e​r​ ​p​a​t​i​e​n​t
	 */
	HEALTH_RECORD: string
	/**
	 * é​d​u​c​a​t​i​o​n​ ​p​o​u​r​ ​l​a​ ​s​a​n​t​é
	 */
	HEALTH_EDUCATION: string
	/**
	 * p​r​é​v​e​n​t​i​o​n
	 */
	PREVENTION: string
	/**
	 * p​r​é​v​e​n​t​i​o​n​ ​e​n​ ​s​a​n​t​é
	 */
	PREVENTIVE_HEALTHCARE: string
	/**
	 * s​y​n​d​r​ô​m​e​ ​d​'​é​p​u​i​s​e​m​e​n​t​ ​p​r​o​f​e​s​s​i​o​n​n​e​l
	 */
	BURNOUT: string
	/**
	 * A​l​i​m​e​n​t​a​t​i​o​n
	 */
	EATING: string
	/**
	 * p​o​l​i​t​i​q​u​e​ ​d​e​ ​c​o​n​f​i​d​e​n​t​i​a​l​i​t​é
	 */
	PRIVACY_POLICY: string
	/**
	 * m​e​n​t​i​o​n​s​ ​l​é​g​a​l​e​s
	 */
	LEGAL_NOTICES: string
	/**
	 * r​e​s​s​o​u​r​c​e​s
	 */
	RESOURCES: string
	/**
	 * l​é​g​a​l
	 */
	LEGAL: string
	/**
	 * t​é​l​é​p​h​o​n​e
	 */
	PHONE: string
	/**
	 * i​t​i​n​é​r​a​i​r​e
	 */
	DIRECTION: string
	/**
	 * o​u​i
	 */
	YES: string
	/**
	 * n​o​n
	 */
	NO: string
	/**
	 * e​t
	 */
	AND: string
	SKELETON: {
		AUTOCOMPLETE: {
			/**
			 * A​u​c​u​n​ ​r​é​s​u​l​t​a​t​ ​t​r​o​u​v​é
			 */
			EMPTY_STATE: string
		}
	}
}

export type TranslationFunctions = {
	/**
	 * Salut {name}! Merci de laisser une étoile si vous aimez ce project: https://github.com/ivanhofer/typesafe-i18n
	 */
	HI: (arg: { name: unknown }) => LocalizedString
	/**
	 * Chargement...
	 */
	LOADING: () => LocalizedString
	HOME: {
		/**
		 * Accueil
		 */
		TITLE: () => LocalizedString
		/**
		 * Bienvenue dans
		 */
		WELCOME: () => LocalizedString
		TEAM: {
			/**
			 * Équipe
			 */
			TITLE: () => LocalizedString
			/**
			 * Notre équipe pluriprofessionnelle s'engage pour votre santé et celle de vos proches.
			 */
			TEXT: () => LocalizedString
		}
		FOOTER: {
			/**
			 * Site en construction. Contacter le développeur:
			 */
			WIP: () => LocalizedString
		}
	}
	CONTACT: {
		/**
		 * Contact
		 */
		TITLE: () => LocalizedString
		/**
		 * Appelez-nous
		 */
		CALL_US: () => LocalizedString
	}
	SITES: {
		/**
		 * Sites
		 */
		TITLE: () => LocalizedString
	}
	/**
	 * Recherche
	 */
	SEARCH: () => LocalizedString
	ADDRESSBOOK: {
		A11Y: {
			/**
			 * Photo de profil de
			 */
			PROFILE_PIC_OF: () => LocalizedString
		}
		/**
		 * Annuaire
		 */
		TITLE: () => LocalizedString
		GEOCODER: {
			/**
			 * Entrer l'adresse de la personne...
			 */
			PLACEHOLDER: () => LocalizedString
		}
		OCCUPATIONS: {
			/**
			 * Sélectionner par profession...
			 */
			PLACEHOLDER: () => LocalizedString
		}
		COMMUNES: {
			/**
			 * Sélectionner par commune...
			 */
			PLACEHOLDER: () => LocalizedString
		}
		FACILITIES: {
			/**
			 * Sélectionner par établissement...
			 */
			PLACEHOLDER: () => LocalizedString
		}
		CATEGORIES: {
			/**
			 * Sélectionner par catégorie....
			 */
			PLACEHOLDER: () => LocalizedString
		}
		SITUATIONS: {
			/**
			 * Selectionner par situation...
			 */
			PLACEHOLDER: () => LocalizedString
		}
		SEARCH: {
			/**
			 * Nom ou prénom
			 */
			LABEL: () => LocalizedString
			/**
			 * Nom ou prénom...
			 */
			PLACEHOLDER: () => LocalizedString
			/**
			 * Recherche par nom ou prénom
			 */
			ARIA_LABEL: () => LocalizedString
		}
		/**
		 * Retourner vers l'annuaire
		 */
		GOTOADDRESSBOOK: () => LocalizedString
		APPOINTMENT: {
			/**
			 * Prendre rendez-vous
			 */
			LABEL: () => LocalizedString
		}
		/**
		 * Lieu d'exercice
		 */
		LOCATION: () => LocalizedString
		/**
		 * Spécialité
		 */
		SPECIALTY: () => LocalizedString
		/**
		 * Effacer
		 */
		CLEAR: () => LocalizedString
		/**
		 * Moyens de paiement
		 */
		PAYMENT_METHODS: () => LocalizedString
		/**
		 * Moyen de paiement
		 */
		PAYMENT_METHOD: () => LocalizedString
		/**
		 * Tarifs et remboursements
		 */
		COSTS_AND_REIMBURSEMENTS: () => LocalizedString
		/**
		 * Tiers payant
		 */
		THIRD_PARTY_PAYER: () => LocalizedString
		/**
		 * Réseaux sociaux
		 */
		SOMED: () => LocalizedString
		/**
		 * langue parlée
		 */
		SPOKEN_LANGUAGE: () => LocalizedString
		/**
		 * langues parlées
		 */
		SPOKEN_LANGUAGES: () => LocalizedString
		/**
		 * informations
		 */
		INFORMATIONS: () => LocalizedString
	}
	NAVBAR: {
		/**
		 * Annuaire
		 */
		ADDRESSBOOK: () => LocalizedString
		/**
		 * Se connecter
		 */
		LOGIN: () => LocalizedString
		/**
		 * Salut
		 */
		HI: () => LocalizedString
		/**
		 * S'enregistrer
		 */
		REGISTER: () => LocalizedString
		/**
		 * Se déconnecter
		 */
		LOGOUT: () => LocalizedString
		/**
		 * À propos
		 */
		ABOUT: () => LocalizedString
		/**
		 * Chronologie
		 */
		TIMELINE: () => LocalizedString
		/**
		 * Projet de santé
		 */
		HEALTH_PROJECT: () => LocalizedString
		/**
		 * Langue
		 */
		LANGUAGE: () => LocalizedString
		/**
		 * Naviguer
		 */
		NAVIGATE: () => LocalizedString
		/**
		 * Aller à l'Accueil
		 */
		GO_HOME: () => LocalizedString
		/**
		 * Thème
		 */
		THEME: () => LocalizedString
	}
	LOGIN: {
		/**
		 * Connexion
		 */
		LOGIN: () => LocalizedString
		/**
		 * Se connecter
		 */
		TOLOGIN: () => LocalizedString
		/**
		 * Pas encore de compte?
		 */
		NOACCOUNT: () => LocalizedString
		/**
		 * Connexion en cours...
		 */
		SIGNINGIN: () => LocalizedString
		/**
		 * Créer un compte
		 */
		CREATEACCOUNT: () => LocalizedString
		/**
		 * Connexion réussie...
		 */
		SUCCESSFUL: () => LocalizedString
		/**
		 * Déconnexion réussie...
		 */
		LOGOUT: () => LocalizedString
	}
	ERROR404: {
		/**
		 * Oups!
		 */
		OOPS: () => LocalizedString
		/**
		 * Page non trouvée.
		 */
		PAGENOTFOUND: () => LocalizedString
		/**
		 * La page que vous cherchez n'existe pas.
		 */
		DOESNOTEXIST: () => LocalizedString
		/**
		 * Retourner à l'accueil
		 */
		HOME: () => LocalizedString
		/**
		 * Revenir en arrière
		 */
		BACK: () => LocalizedString
	}
	/**
	 * Adresse e-mail
	 */
	EMAILADDRESS: () => LocalizedString
	TIMELINE: {
		/**
		 * Chronologie
		 */
		TITLE: () => LocalizedString
	}
	/**
	 * Mot de passe
	 */
	PASSWORD: () => LocalizedString
	USER: {
		/**
		 * Profil de {userName}
		 */
		PROFILE: (arg: { userName: string }) => LocalizedString
		/**
		 * Rôle
		 */
		ROLE: () => LocalizedString
	}
	FACILITY: {
		/**
		 * Maison de santé
		 */
		OUTPATIENT_CLINIC: () => LocalizedString
	}
	BLOG: {
		/**
		 * Lire la suite
		 */
		READMORE: () => LocalizedString
	}
	OUTPATIENT_CLINIC: {
		/**
		 * réunion de concertation pluriprofessionnelle
		 */
		MDT_MEETING: () => LocalizedString
		/**
		 * éducation thérapeutique du patient
		 */
		TPE: () => LocalizedString
		/**
		 * programmes
		 */
		PROGRAMS: () => LocalizedString
		/**
		 * notre programme
		 */
		OUR_PROGRAM: () => LocalizedString
		/**
		 * nos programmes
		 */
		OUR_PROGRAMS: () => LocalizedString
		/**
		 * notre autre programme
		 */
		OUR_OTHER_PROGRAM: () => LocalizedString
		/**
		 * nos autres programmes
		 */
		OUR_OTHER_PROGRAMS: () => LocalizedString
	}
	DISEASE: {
		/**
		 * diabète
		 */
		DIABETES: () => LocalizedString
		/**
		 * cancer
		 */
		CANCER: () => LocalizedString
	}
	/**
	 * site web
	 */
	WEBSITE: () => LocalizedString
	/**
	 * En savoir plus
	 */
	LEARN_MORE: () => LocalizedString
	/**
	 * lexique
	 */
	LEXICON: () => LocalizedString
	/**
	 * dossier patient
	 */
	HEALTH_RECORD: () => LocalizedString
	/**
	 * éducation pour la santé
	 */
	HEALTH_EDUCATION: () => LocalizedString
	/**
	 * prévention
	 */
	PREVENTION: () => LocalizedString
	/**
	 * prévention en santé
	 */
	PREVENTIVE_HEALTHCARE: () => LocalizedString
	/**
	 * syndrôme d'épuisement professionnel
	 */
	BURNOUT: () => LocalizedString
	/**
	 * Alimentation
	 */
	EATING: () => LocalizedString
	/**
	 * politique de confidentialité
	 */
	PRIVACY_POLICY: () => LocalizedString
	/**
	 * mentions légales
	 */
	LEGAL_NOTICES: () => LocalizedString
	/**
	 * ressources
	 */
	RESOURCES: () => LocalizedString
	/**
	 * légal
	 */
	LEGAL: () => LocalizedString
	/**
	 * téléphone
	 */
	PHONE: () => LocalizedString
	/**
	 * itinéraire
	 */
	DIRECTION: () => LocalizedString
	/**
	 * oui
	 */
	YES: () => LocalizedString
	/**
	 * non
	 */
	NO: () => LocalizedString
	/**
	 * et
	 */
	AND: () => LocalizedString
	SKELETON: {
		AUTOCOMPLETE: {
			/**
			 * Aucun résultat trouvé
			 */
			EMPTY_STATE: () => LocalizedString
		}
	}
}

export type Formatters = {}
