# Generated by Django 4.0.3 on 2022-04-03 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mesh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('label', models.CharField(max_length=36, unique=True)),
                ('description', models.CharField(blank=True, max_length=72, null=True)),
                ('mesh', models.ForeignKey(blank=True, help_text='Category as a MeSH heading', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='mesh.mesh')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
