# Generated by Django 4.0.4 on 2022-04-26 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0002_edgeset_networkedge_nodeset_networknode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networknode',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
