# Generated by Django 4.0.4 on 2022-05-13 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mesh', '0001_initial'),
        ('workforce', '0004_networkedge_facilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='networknode',
            name='mesh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mesh.mesh'),
        ),
    ]
