# Generated by Django 4.0.4 on 2022-05-16 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0005_networknode_mesh'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthpersonnel',
            name='description_en',
            field=models.CharField(blank=True, max_length=72, null=True),
        ),
        migrations.AddField(
            model_name='healthpersonnel',
            name='description_fr',
            field=models.CharField(blank=True, max_length=72, null=True),
        ),
        migrations.AddField(
            model_name='healthpersonnel',
            name='label_en',
            field=models.CharField(max_length=36, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='healthpersonnel',
            name='label_fr',
            field=models.CharField(max_length=36, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='networknode',
            name='label',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
