# Generated by Django 4.0.4 on 2022-05-16 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0006_healthpersonnel_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='networknode',
            name='label_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='networknode',
            name='label_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
