# Generated by Django 4.0.4 on 2022-05-17 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0009_label_gender_label_grammatical_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French')], default='en', max_length=2),
        ),
    ]
