# Generated by Django 4.0.4 on 2022-05-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0010_label_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='workforcenetworkedgefacilities',
            name='public_facing',
            field=models.BooleanField(default=False, help_text='Should the user node included in this edge be public?'),
        ),
    ]
