# Generated by Django 4.0.6 on 2022-08-11 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0004_organization_remove_facility_category_and_more'),
        ('workforce', '0011_workforcenetworkedgefacilities_public_facing'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkforceNetworkedgeOrganizations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_facing', models.BooleanField(default=False, help_text='Should the user node included in this edge be public?')),
            ],
            options={
                'db_table': 'workforce_networkedge_organizations',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='networkedge',
            name='facilities',
        ),
        migrations.AddField(
            model_name='networkedge',
            name='organizations',
            field=models.ManyToManyField(through='workforce.WorkforceNetworkedgeOrganizations', to='facility.organization'),
        ),
        migrations.DeleteModel(
            name='WorkforceNetworkedgeFacilities',
        ),
        migrations.AddField(
            model_name='workforcenetworkedgeorganizations',
            name='networkedge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='workforce.networkedge'),
        ),
        migrations.AddField(
            model_name='workforcenetworkedgeorganizations',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='facility.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='workforcenetworkedgeorganizations',
            unique_together={('networkedge', 'organization')},
        ),
    ]
