# Generated by Django 4.1 on 2022-09-05 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0007_facility'),
        ('workforce', '0012_workforcenetworkedgeorganizations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkforceNetworkedgeFacilities',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_facing', models.BooleanField(default=False, help_text='Should the user node included in this edge be public?')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='facility.facility')),
                ('networkedge', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='workforce.networkedge')),
            ],
            options={
                'db_table': 'workforce_networkedge_facilities',
                'managed': True,
                'unique_together': {('networkedge', 'facility')},
            },
        ),
    ]
