# Generated by Django 4.1 on 2022-09-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0007_facility'),
        ('workforce', '0013_workforcenetworkedgefacilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkedge',
            name='facilities',
            field=models.ManyToManyField(through='workforce.WorkforceNetworkedgeFacilities', to='facility.facility'),
        ),
    ]
