# Generated by Django 4.1.1 on 2022-09-30 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0015_networkedge_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkedge',
            name='roles',
        ),
    ]
