# Generated by Django 4.1.1 on 2022-09-30 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_role_description_en_role_description_fr_and_more'),
        ('workforce', '0016_remove_networkedge_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='workforcenetworkedgeorganizations',
            name='roles',
            field=models.ManyToManyField(blank=True, help_text='Roles allowed so see the related object', to='access.role'),
        ),
    ]
