# Generated by Django 4.1.1 on 2022-09-30 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0011_organization_formatted_name_definite_article_en_and_more'),
        ('workforce', '0017_workforcenetworkedgeorganizations_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workforcenetworkedgeorganizations',
            name='networkedge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='networkedge_organizations', to='workforce.networkedge'),
        ),
        migrations.AlterField(
            model_name='workforcenetworkedgeorganizations',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='networkedge_organizations', to='facility.organization'),
        ),
    ]
