# Generated by Django 4.1.7 on 2023-04-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0018_alter_workforcenetworkedgeorganizations_networkedge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='networknode',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
