# Generated by Django 4.1.7 on 2023-04-13 13:28

from django.db import migrations
from django.template.defaultfilters import slugify

def populate_posts_slug_field(apps, schema_editor):
    MyModel = apps.get_model('workforce', 'NetworkNode')
    for node in MyModel.objects.all():
        node.slug = slugify(node.name)
        node.save()

class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0019_networknode_slug'),
    ]

    operations = [
        migrations.RunPython(populate_posts_slug_field, migrations.RunPython.noop),
    ]
