# Generated by Django 4.1.8 on 2023-04-13 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0022_remove_networknode_slug_workforceslug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workforceslug',
            name='node',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slug', to='workforce.networknode'),
        ),
    ]
