# Generated by Django 4.1.9 on 2023-05-05 00:34

from django.db import migrations, models
import django.db.models.deletion
import workforce.models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0023_alter_workforceslug_node'),
    ]

    operations = [
        migrations.CreateModel(
            name='RPPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, max_length=11, null=True, validators=[workforce.models.validate_rpps_isdigit, workforce.models.validate_rpps_length], verbose_name='RPPS number')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rpps', to='workforce.networknode')),
            ],
        ),
    ]
