# Generated by Django 4.1.9 on 2023-05-05 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0024_rpps'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rpps',
            options={'verbose_name_plural': 'RPPS'},
        ),
        migrations.AlterField(
            model_name='rpps',
            name='node',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rpps', to='workforce.networknode'),
        ),
    ]
