# Generated by Django 4.1.9 on 2023-05-06 23:14

from django.db import migrations, models
import workforce.models.french


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0027_alter_cartevitale_node'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('definition', models.CharField(blank=True, max_length=255, null=True)),
                ('professional', models.ManyToManyField(limit_choices_to=workforce.models.french.limit_to_users, to='workforce.networknode')),
            ],
        ),
        migrations.AddConstraint(
            model_name='convention',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_name'),
        ),
    ]
