# Generated by Django 4.1.9 on 2023-05-06 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0028_convention_convention_unique_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='convention',
            old_name='professional',
            new_name='profession',
        ),
    ]
