# Generated by Django 4.1.9 on 2023-05-06 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0029_rename_professional_convention_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convention',
            name='definition',
            field=models.TextField(blank=True, null=True),
        ),
    ]
