# Generated by Django 4.1.9 on 2023-05-07 03:35

from django.db import migrations, models
import django.db.models.deletion
import workforce.models.french


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0015_organization_company_name'),
        ('workforce', '0030_alter_convention_definition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conventionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convention', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workforce.convention')),
                ('node', models.ForeignKey(limit_choices_to=workforce.models.french.limit_to_users, on_delete=django.db.models.deletion.CASCADE, to='workforce.networknode')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facility.organization')),
            ],
        ),
        migrations.AddConstraint(
            model_name='conventionnement',
            constraint=models.UniqueConstraint(fields=('node', 'organization'), name='unique_node_organization'),
        ),
    ]
