# Generated by Django 4.1.9 on 2023-05-07 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0031_conventionnement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('label_en', models.CharField(blank=True, max_length=255, null=True)),
                ('label_fr', models.CharField(blank=True, max_length=255, null=True)),
                ('definition', models.TextField(blank=True, null=True)),
                ('definition_en', models.TextField(blank=True, null=True)),
                ('definition_fr', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_payment_name'),
        ),
    ]
