# Generated by Django 4.1.9 on 2023-05-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0034_alter_convention_profession_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdPartyPayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('label_en', models.CharField(blank=True, max_length=255, null=True)),
                ('label_fr', models.CharField(blank=True, max_length=255, null=True)),
                ('definition', models.TextField(blank=True, null=True)),
                ('definition_en', models.TextField(blank=True, null=True)),
                ('definition_fr', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Third-party payers',
            },
        ),
        migrations.AddConstraint(
            model_name='thirdpartypayer',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_third_party_payer_name'),
        ),
    ]
