# Generated by Django 4.1.9 on 2023-05-09 23:44

from django.db import migrations, models
import django.db.models.deletion
import workforce.models.limit_choices


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0015_organization_company_name'),
        ('workforce', '0035_thirdpartypayer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdPartyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(null=True)),
                ('node', models.ForeignKey(limit_choices_to=workforce.models.limit_choices.limit_to_users, on_delete=django.db.models.deletion.CASCADE, to='workforce.networknode')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facility.organization')),
                ('payer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workforce.thirdpartypayer')),
            ],
            options={
                'verbose_name_plural': 'Third-party payments',
            },
        ),
        migrations.AddConstraint(
            model_name='thirdpartypayment',
            constraint=models.UniqueConstraint(fields=('node', 'organization', 'payer'), name='unique_third_party_payment_node_organization_payer'),
        ),
    ]
