# Generated by Django 4.1.9 on 2023-05-11 02:00

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import workforce.models.limit_choices


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0036_thirdpartypayment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpokenLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), help_text='Enter a language code or a natural language name.', size=None)),
                ('node', models.ForeignKey(limit_choices_to=workforce.models.limit_choices.limit_to_users, on_delete=django.db.models.deletion.CASCADE, to='workforce.networknode')),
            ],
        ),
    ]
