# Generated by Django 4.1.9 on 2023-05-23 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0039_adeli'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workforcenetworkedgeorganizations',
            name='networkedge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networkedge_organizations', to='workforce.networkedge'),
        ),
    ]
