# Generated by Django 4.0.4 on 2022-05-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_rejectslug_alter_slug_slug'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='slug',
            constraint=models.UniqueConstraint(fields=('slug', 'site', 'user'), name='unique_directory_slug_per_site_per_user'),
        ),
    ]
