# Generated by Django 4.1.5 on 2023-01-10 04:19

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_alter_timeline_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='content',
            field=wagtail.fields.StreamField([('slide', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Add your title', required=True)), ('slides', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('title', wagtail.blocks.CharBlock(max_length=40, required=True)), ('start_date', wagtail.blocks.DateBlock(help_text='Start date: required', required=True)), ('start_time', wagtail.blocks.TimeBlock(help_text='Start time: optional', required=False)), ('end_date', wagtail.blocks.DateBlock(help_text='End date: optional', required=False)), ('end_time', wagtail.blocks.TimeBlock(help_text='End time: optional', required=False)), ('display_date', wagtail.blocks.CharBlock(help_text="A string for presenting the date. This value will be presented exactly as specified, overriding TimelineJS's default date formatting. Note that the year property, at a minimum, must still be provided so that TimelineJS can properly position the event on the actual timeline.", max_length=40, required=False)), ('format', wagtail.blocks.CharBlock(help_text="A formatting string which will be used to render the date parts, if you wish to override TimelineJS's default formatting.", max_length=40, required=False)), ('text', wagtail.blocks.TextBlock(max_length=200, required=True)), ('more_text', wagtail.blocks.TextBlock(required=False)), ('page_url', wagtail.blocks.PageChooserBlock(required=False)), ('web_url', wagtail.blocks.URLBlock(help_text='If the button page above is selected, that will be used first.', required=False))])))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
