# Generated by Django 4.1.5 on 2023-01-11 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_alter_timeline_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeline',
            name='banner_image',
        ),
    ]
