# Generated by Django 4.1.5 on 2023-01-27 14:13

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0019_pagecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='cms.pagecategory'),
        ),
    ]
