# Generated by Django 4.1.5 on 2023-01-27 14:20

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_timeline_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='cms.pagecategory'),
        ),
    ]
