# Generated by Django 4.1.5 on 2023-01-27 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0021_homepage_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='categories',
        ),
        migrations.AddField(
            model_name='homepage',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.pagecategory'),
        ),
    ]
