# Generated by Django 4.1.5 on 2023-01-27 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0023_remove_timeline_categories_timeline_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homepages', to='cms.pagecategory'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timelines', to='cms.pagecategory'),
        ),
    ]
