# Generated by Django 4.1.7 on 2023-03-16 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_grammaticalgender_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('label_en', models.CharField(max_length=255, null=True)),
                ('label_fr', models.CharField(max_length=255, null=True)),
                ('to_label', models.CharField(max_length=255)),
                ('to_label_en', models.CharField(max_length=255, null=True)),
                ('to_label_fr', models.CharField(max_length=255, null=True)),
                ('from_label', models.CharField(max_length=255)),
                ('from_label_en', models.CharField(max_length=255, null=True)),
                ('from_label_fr', models.CharField(max_length=255, null=True)),
                ('grammatical_number', models.CharField(blank=True, choices=[('S', 'Singular'), ('P', 'Plural')], max_length=1)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.grammaticalgender')),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
        ),
    ]
