# Generated by Django 4.0.3 on 2022-04-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='website_title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
