# Generated by Django 4.0.6 on 2022-08-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0003_facility_node'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('formatted_name', models.CharField(max_length=255, unique=True)),
                ('website_title', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(blank=True, help_text='ISO language code', max_length=3)),
            ],
            options={
                'verbose_name_plural': 'Organizations',
            },
        ),
        migrations.RemoveField(
            model_name='facility',
            name='category',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='node',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='site',
        ),
    ]
