# Generated by Django 4.0.6 on 2022-08-11 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0012_workforcenetworkedgeorganizations_and_more'),
        ('addressbook', '0011_appointment_organization_email_organization_and_more'),
        ('sites', '0002_alter_domain_unique'),
        ('facility', '0004_organization_remove_facility_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Facility',
        ),
        migrations.AddField(
            model_name='organization',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organization', to='facility.category'),
        ),
        migrations.AddField(
            model_name='organization',
            name='contact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organisation', to='addressbook.contact'),
        ),
        migrations.AddField(
            model_name='organization',
            name='node',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workforce.networknode'),
        ),
        migrations.AddField(
            model_name='organization',
            name='site',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='sites.site'),
        ),
    ]
