# Generated by Django 4.0.6 on 2022-08-14 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0012_workforcenetworkedgeorganizations_and_more'),
        ('facility', '0005_delete_facility_organization_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workforce.networknode'),
        ),
    ]
