# Generated by Django 4.1.1 on 2022-09-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0007_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='registration',
            field=models.BooleanField(default=False),
        ),
    ]
