# Generated by Django 4.1.1 on 2022-09-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0008_organization_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='formatted_name_definite_article',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
