# Generated by Django 4.1.1 on 2022-09-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0009_organization_formatted_name_definite_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='formatted_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='organization',
            name='website_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
