# Generated by Django 4.1.1 on 2022-09-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0010_alter_organization_formatted_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='formatted_name_definite_article_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='formatted_name_definite_article_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='formatted_name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='formatted_name_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='website_title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='website_title_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
