# Generated by Django 4.1.1 on 2022-10-14 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0011_organization_formatted_name_definite_article_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='google_site_verification',
            field=models.CharField(blank=True, help_text='Google site verification meta tag', max_length=255),
        ),
    ]
