# Generated by Django 4.1.9 on 2023-05-12 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0015_organization_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='website_description',
            field=models.TextField(blank=True),
        ),
    ]
