# Generated by Django 4.0.4 on 2022-05-31 01:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccessControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(15)])),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='access.endpoint')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='access.role')),
            ],
        ),
        migrations.AddConstraint(
            model_name='accesscontrol',
            constraint=models.UniqueConstraint(fields=('endpoint', 'role'), name='unique_accesscontrol_endpoint_role'),
        ),
    ]
