# Generated by Django 4.0.6 on 2022-07-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_role_description_role_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='label_en',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='label_fr',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
