# Generated by Django 4.0.4 on 2022-05-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_bio_alter_user_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='grammatical_gender',
            field=models.CharField(choices=[('F', 'Feminine'), ('M', 'Masculine'), ('N', 'Neutral')], max_length=1, null=True),
        ),
    ]
