# Generated by Django 4.0.4 on 2022-05-16 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_grammatical_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammaticalGender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('label_en', models.CharField(max_length=255, null=True)),
                ('label_fr', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
