# Generated by Django 4.0.4 on 2022-05-16 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_grammaticalgender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='grammatical_gender',
        ),
    ]
