# Generated by Django 4.0.4 on 2022-05-16 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_grammatical_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='grammatical_gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.grammaticalgender'),
        ),
    ]
