# Generated by Django 4.1.1 on 2022-10-01 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_grammatical_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammaticalgender',
            name='code',
            field=models.CharField(default='', max_length=1),
            preserve_default=False,
        ),
    ]
