// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'fr'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * Hi {name}! Please leave a star if you like this project: https://github.com/ivanhofer/typesafe-i18n
	 * @param {string} name
	 */
	HI: RequiredParams<'name'>
	/**
	 * Welcome
	 */
	WELCOME: string
	/**
	 * Search
	 */
	SEARCH: string
	ADDRESSBOOK: {
		OCCUPATIONS: {
			/**
			 * Select by profession...
			 */
			PLACEHOLDER: string
		}
		SEARCH: {
			/**
			 * Search
			 */
			LABEL: string
			/**
			 * last name or first name
			 */
			PLACEHOLDER: string
		}
	}
}

export type TranslationFunctions = {
	/**
	 * Hi {name}! Please leave a star if you like this project: https://github.com/ivanhofer/typesafe-i18n
	 */
	HI: (arg: { name: string }) => LocalizedString
	/**
	 * Welcome
	 */
	WELCOME: () => LocalizedString
	/**
	 * Search
	 */
	SEARCH: () => LocalizedString
	ADDRESSBOOK: {
		OCCUPATIONS: {
			/**
			 * Select by profession...
			 */
			PLACEHOLDER: () => LocalizedString
		}
		SEARCH: {
			/**
			 * Search
			 */
			LABEL: () => LocalizedString
			/**
			 * last name or first name
			 */
			PLACEHOLDER: () => LocalizedString
		}
	}
}

export type Formatters = {}
