// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'fr'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * Hi {name}! Please leave a star if you like this project: https://github.com/ivanhofer/typesafe-i18n
	 * @param {string} name
	 */
	HI: RequiredParams<'name'>
	HOME: {
		/**
		 * Welcome to
		 */
		WELCOME: string
		TEAM: {
			/**
			 * Our team
			 */
			TITLE: string
			/**
			 * The members of our multidisciplinary team are working together to deliver comprehensive care to you and your relatives.
			 */
			TEXT: string
		}
	}
	/**
	 * Search
	 */
	SEARCH: string
	ADDRESSBOOK: {
		/**
		 * Address book
		 */
		TITLE: string
		OCCUPATIONS: {
			/**
			 * Select by profession...
			 */
			PLACEHOLDER: string
		}
		SEARCH: {
			/**
			 * Search
			 */
			LABEL: string
			/**
			 * last name or first name
			 */
			PLACEHOLDER: string
		}
		/**
		 * Go back to addressbook
		 */
		GOTOADDRESSBOOK: string
		APPOINTMENT: {
			/**
			 * Book an appointment
			 */
			LABEL: string
		}
		/**
		 * Clinic location
		 */
		LOCATION: string
		/**
		 * specialty
		 */
		SPECIALTY: string
	}
	NAVBAR: {
		/**
		 * Addressbook
		 */
		ADDRESSBOOK: string
		/**
		 * Login
		 */
		LOGIN: string
		/**
		 * Register
		 */
		REGISTER: string
		/**
		 * Logout
		 */
		LOGOUT: string
	}
	LOGIN: {
		/**
		 * Login
		 */
		LOGIN: string
		/**
		 * Login
		 */
		TOLOGIN: string
		/**
		 * No account yet?
		 */
		NOACCOUNT: string
		/**
		 * Signing in...
		 */
		SIGNINGIN: string
		/**
		 * Create an account
		 */
		CREATEACCOUNT: string
	}
	/**
	 * Email address
	 */
	EMAILADDRESS: string
	/**
	 * Password
	 */
	PASSWORD: string
}

export type TranslationFunctions = {
	/**
	 * Hi {name}! Please leave a star if you like this project: https://github.com/ivanhofer/typesafe-i18n
	 */
	HI: (arg: { name: string }) => LocalizedString
	HOME: {
		/**
		 * Welcome to
		 */
		WELCOME: () => LocalizedString
		TEAM: {
			/**
			 * Our team
			 */
			TITLE: () => LocalizedString
			/**
			 * The members of our multidisciplinary team are working together to deliver comprehensive care to you and your relatives.
			 */
			TEXT: () => LocalizedString
		}
	}
	/**
	 * Search
	 */
	SEARCH: () => LocalizedString
	ADDRESSBOOK: {
		/**
		 * Address book
		 */
		TITLE: () => LocalizedString
		OCCUPATIONS: {
			/**
			 * Select by profession...
			 */
			PLACEHOLDER: () => LocalizedString
		}
		SEARCH: {
			/**
			 * Search
			 */
			LABEL: () => LocalizedString
			/**
			 * last name or first name
			 */
			PLACEHOLDER: () => LocalizedString
		}
		/**
		 * Go back to addressbook
		 */
		GOTOADDRESSBOOK: () => LocalizedString
		APPOINTMENT: {
			/**
			 * Book an appointment
			 */
			LABEL: () => LocalizedString
		}
		/**
		 * Clinic location
		 */
		LOCATION: () => LocalizedString
		/**
		 * specialty
		 */
		SPECIALTY: () => LocalizedString
	}
	NAVBAR: {
		/**
		 * Addressbook
		 */
		ADDRESSBOOK: () => LocalizedString
		/**
		 * Login
		 */
		LOGIN: () => LocalizedString
		/**
		 * Register
		 */
		REGISTER: () => LocalizedString
		/**
		 * Logout
		 */
		LOGOUT: () => LocalizedString
	}
	LOGIN: {
		/**
		 * Login
		 */
		LOGIN: () => LocalizedString
		/**
		 * Login
		 */
		TOLOGIN: () => LocalizedString
		/**
		 * No account yet?
		 */
		NOACCOUNT: () => LocalizedString
		/**
		 * Signing in...
		 */
		SIGNINGIN: () => LocalizedString
		/**
		 * Create an account
		 */
		CREATEACCOUNT: () => LocalizedString
	}
	/**
	 * Email address
	 */
	EMAILADDRESS: () => LocalizedString
	/**
	 * Password
	 */
	PASSWORD: () => LocalizedString
}

export type Formatters = {}
